# Site settings
title: Churchill Cloud
email: contact@churchillcloud.com
description: >-
  Full featured cloud with privacy as a priority. Churchill Cloud—secured by Cryptogray™

# URLs - keep blank for both local development and Netlify
url: ""
baseurl: ""

# For production (uncomment when deploying to churchillcloud.com):
# url: "https://churchillcloud.com"
# baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
    layout: default

# Include/Exclude settings
include:
  - ./_pages

# Directory settings
source: .
layouts_dir: _layouts

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .gitignore
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
