title: Churchill Cloud
email: contact@churchillcloud.com
description: >-
  Full featured cloud with privacy as a priority. Churchill Cloud—secured by Cryptogray™
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's domain

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
