on:
  push:
    branches:
      - main
      - master
      - devel/*
      - issue/*
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build and deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Build
        run: nix build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: churchillcloud-com
          directory: result
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
